export default function Head() {
    return (
        <>
            <title>Muzzlof</title>
            <meta content="width=device-width, initial-scale=1" name="viewport"/>
            <meta name="description" content="Generated by create next app"/>
            <link rel="shortcut icon" href="assets/images/tab_icon.svg"/>

        </>
    )
}
